package com.roofnfloor.roofnfloorz.utility;

public class Defaults {

	public static String SERVER_URL = "https://roofsnfloors.com:8080/";
	public static String DEFAULT_CITY_IMAGE = "assets/image/defaults/default-city.jpg";
	public static String DEFAULT_PROPERTY_IMAGE = "assets/image/defaults/default-property.jpg";
	public static String CITY_NAME[] = {"Adilabad",
		    "Bhadradri Kothagudem",
		    "Hyderabad",
		    "Jagitial",
		    "Jangaon",
		    "Jayashankar Bhupalpally",
		    "Jogulamba Gadwal",
		    "Kamareddy",
		    "Karimnagar",
		    "Khammam",
		    "Komaram Bheem",
		    "Mahabubabad",
		    "Mahabubnagar",
		    "Mancherial",
		    "Medak",
		    "Medchal–Malkajgiri",
		    "Mulugu",
		    "Nagarkurnool",
		    "Narayanpet",
		    "Nalgonda",
		    "Nirmal",
		    "Nizamabad",
		    "Peddapalli",
		    "Rajanna Sircilla",
		    "Ranga Reddy",
		    "Shamshabad",
		    "Sangareddy",
		    "Shamirpet",
		    "Siddipet",
		    "Suryapet",
		    "Vikarabad",
		    "Wanaparthy",
		    "Warangal Rural",
		    "Warangal Urban",
		    "Yadadri Bhuvanagiri",
		    "Ramagundam",
		    "Miryalaguda",
		    "Rajamahendravaram",
		    "Vijayawada",
		    "Chittoor",
		    "Anantapur",
		    "East Godavari",
		    "Guntur",
		    "YSR Kadapa district",
		    "Krishna",
		    "Kurnool",
		    "Nellore",
		    "Prakasam",
		    "Srikakulam",
		    "Visakhapatnam",
		    "Vizianagaram",
		    "West Godavari",
		    "Eluru",
		    "Ongole",
		    "Machilipatnam",
		    "Kadapa",
		    "Kakinada",
		    "Tirupati",
		    "Anantapuram",
		    "Nandyal",
		    "Proddatur",
		    "Adoni",
		    "Madanapalle",
		    "Chirala",
		    "Tenali",
		    "Hindupur",
		    "Bhimavaram",
		    "Guntakal",
		    "Dharmavaram",
		    "Gudivada",
		    "Narasaraopet",
		    "Tadipatri",
		    "Mangalagiri",
		    "Tadepalligudem",
		    "Chilakaluripet",
		    "Yemmiganur"};
	public static String CITY_IMAGE[] = {"1.jpg",
		    "2.jpg",
		    "3.jpg",
		    "4.jpg",
		    "Jangaon",
		    "Jayashankar Bhupalpally",
		    "Jogulamba Gadwal",
		    "Kamareddy",
		    "Karimnagar",
		    "Khammam",
		    "Komaram Bheem",
		    "Mahabubabad",
		    "Mahabubnagar",
		    "Mancherial",
		    "Medak",
		    "Medchal–Malkajgiri",
		    "Mulugu",
		    "Nagarkurnool",
		    "Narayanpet",
		    "Nalgonda",
		    "Nirmal",
		    "Nizamabad",
		    "Peddapalli",
		    "Rajanna Sircilla",
		    "Ranga Reddy",
		    "Shamshabad",
		    "Sangareddy",
		    "Shamirpet",
		    "Siddipet",
		    "Suryapet",
		    "Vikarabad",
		    "Wanaparthy",
		    "Warangal Rural",
		    "Warangal Urban",
		    "Yadadri Bhuvanagiri",
		    "Ramagundam",
		    "Miryalaguda",
		    "Rajamahendravaram",
		    "Vijayawada",
		    "Chittoor",
		    "Anantapur",
		    "East Godavari",
		    "Guntur",
		    "YSR Kadapa district",
		    "Krishna",
		    "Kurnool",
		    "Nellore",
		    "Prakasam",
		    "Srikakulam",
		    "Visakhapatnam",
		    "Vizianagaram",
		    "West Godavari",
		    "Eluru",
		    "Ongole",
		    "Machilipatnam",
		    "Kadapa",
		    "Kakinada",
		    "Tirupati",
		    "Anantapuram",
		    "Nandyal",
		    "Proddatur",
		    "Adoni",
		    "Madanapalle",
		    "Chirala",
		    "Tenali",
		    "Hindupur",
		    "Bhimavaram",
		    "Guntakal",
		    "Dharmavaram",
		    "Gudivada",
		    "Narasaraopet",
		    "Tadipatri",
		    "Mangalagiri",
		    "Tadepalligudem",
		    "Chilakaluripet",
		    "Yemmiganur"};
	public static String CITY_STATE[] = {"Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Telangana",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh",
		    "Andhra Pradesh"
		    };
	public static String CITY_CODE[] = {"Adilabad",
		    "Bhadradri Kothagudem",
		    "Hyderabad",
		    "Jagitial",
		    "Jangaon",
		    "Jayashankar Bhupalpally",
		    "Jogulamba Gadwal",
		    "Kamareddy",
		    "Karimnagar",
		    "Khammam",
		    "Komaram Bheem",
		    "Mahabubabad",
		    "Mahabubnagar",
		    "Mancherial",
		    "Medak",
		    "Medchal–Malkajgiri",
		    "Mulugu",
		    "Nagarkurnool",
		    "Narayanpet",
		    "Nalgonda",
		    "Nirmal",
		    "Nizamabad",
		    "Peddapalli",
		    "Rajanna Sircilla",
		    "Ranga Reddy",
		    "Shamshabad",
		    "Sangareddy",
		    "Shamirpet",
		    "Siddipet",
		    "Suryapet",
		    "Vikarabad",
		    "Wanaparthy",
		    "Warangal Rural",
		    "Warangal Urban",
		    "Yadadri Bhuvanagiri",
		    "Ramagundam",
		    "Miryalaguda",
		    "Rajamahendravaram",
		    "Vijayawada",
		    "Chittoor",
		    "Anantapur",
		    "East Godavari",
		    "Guntur",
		    "YSR Kadapa district",
		    "Krishna",
		    "Kurnool",
		    "Nellore",
		    "Prakasam",
		    "Srikakulam",
		    "Visakhapatnam",
		    "Vizianagaram",
		    "West Godavari",
		    "Eluru",
		    "Ongole",
		    "Machilipatnam",
		    "Kadapa",
		    "Kakinada",
		    "Tirupati",
		    "Anantapuram",
		    "Nandyal",
		    "Proddatur",
		    "Adoni",
		    "Madanapalle",
		    "Chirala",
		    "Tenali",
		    "Hindupur",
		    "Bhimavaram",
		    "Guntakal",
		    "Dharmavaram",
		    "Gudivada",
		    "Narasaraopet",
		    "Tadipatri",
		    "Mangalagiri",
		    "Tadepalligudem",
		    "Chilakaluripet",
		    "Yemmiganur"};
}
